### PR TITLE
Fix Permission denied wyze_config.ini

### PR DESCRIPTION
**Pull request by leoledmag**
In Home Assistant Core, the current path is wrong because "ha" can't write.

With this change now wyze_config.ini will move to custom_component/wyzeapi/wyze_config.ini

This should work for all versions

### CODE REVIEW

**Comment by leoledmag** [comment]
More details here: https://github.com/JoshuaMulliken/ha-wyzeapi/issues/217

**Comment by JoshuaMulliken** [comment]
@leoledmag Thanks for the contribution!

The file is currently stored in the main config path next to `configuration.yaml` is it possible to modify your PR to put the file there so that people with standard HASSIO or docker-based installs will not get duplicated devices?

**Comment by leoledmag** [comment]
Yea of course let me check and I will change to keep next to configuration.yalm I will keep you updated

**Comment by leoledmag** [comment]
Now it's ok, with hass.config.path('wyze_config.ini') the wyze_config.ini will be saved next to configuration.yalm. And will works for all versions.

**Review by JoshuaMulliken — APPROVED** [review]
Fantastic! Thank you so much

**Pull request merged**
