### PR TITLE
Support for Floodlight - Requires PR #45 in wyzeapy

### LINKED ISSUE #290: [Feature Request] Wyze Floodlight
Basic Floodlight support. (On/off, maybe brightness support)

### PR DESCRIPTION
**Pull request by jdeath**
should close #290

### CODE REVIEW

**Comment by yoinx** [comment]
Gotta be honest... I hate that wyze is listing these floodlights in the cameras list. Not much you can do about that though. 

I commented on your PR in wyzeapy. I'm not 100% sure setting the property there like you are should actually be doing anything to the light, even if it's reflected as such in Home Assistant.

**Comment by jdeath** [comment]
I guarantee it works. Question: Any objection to putting the URL of the thumbnail of the last 5 motion events into a property of the camera? That seems pretty easy and useful to have in homeassistant. Getting the video file is a work in progress, but the image is trivial.

**Comment by yoinx** [comment]
I actually have fairly minimal involvement in the project at the moment, mostly just lurking on GitHub.

I don't see why you wouldn't be able to do that, though it's outside of the scope of this commit. However, I will say that it may have a fairly significant impact to the number of API queries (too many will end up getting this integration blocked by Wyze, see the binary sensor fiasco).

I know I ended up firing an event down the event bus when the cameras get a new event. This event included the image and video urls. I don't remember adding any extra calls for it, but I also don't recall it having all the events (it's been awhile) in a particularly clean way. So you may have to manually cache them in the objects as your parse the list each time. It was an events endpoint that lists them as in the events list in the app. I think you can pass a parameter to limit it to 1 camera at a time, but then you're creating 1 query per camera during the updates. With one camera, meh. It's 2 queries each cycle. With 30, it would be 60. Currently, it's 1 for any number.

Just food for thought.

**Comment by jdeath** [comment]
Thanks. I gave up because the wyze motion events triggers on everything for my camera, even if filter on both PIR and camera motion. However, the URL of the thumbnail is returned in the _get_event_list() function call. It is just buried in response['data']['event_list'][x]['file_list'][0]['url'] , so no extra calls are needed. The video I see how to get, but can't quite get it to work, so gave up. I think it just requires 2 more API calls.

**Review by JoshuaMulliken — APPROVED** [review]
Looks good to me! cool new feature!

**Comment by jscherry** [comment]
Do I need to downloand anything else to get the floodlight working? I saw this note in the release:
Requires PR https://github.com/JoshuaMulliken/ha-wyzeapi/pull/45 in wyzeapy by @jdeath in https://github.com/JoshuaMulliken/ha-wyzeapi/pull/361

**Comment by jdeath** [comment]
No, just update the homeassistant integration. The integration should automatically get the updated python library, since the author linked them in the manifest. I am still using my local version, but hopefully the new one will work for you.

**Pull request merged**
