### PR TITLE
Fixing redundant & incorrect 'or' pipe statement

### PR DESCRIPTION
**Pull request by ninadpchaudhari**
Fixing Issue #311

### CODE REVIEW

**Comment by ninadpchaudhari** [comment]
Btw it seems we are setting `self.enabled` to `True` none-the-less, 
Why not just change both lines to `self.enabled = True`. Is there a reason for updating the same only if its `Falsy`?

**Comment by yoinx** [comment]
> Btw it seems we are setting `self.enabled` to `True` none-the-less, Why not just remove both lines and add `self.enabled = True`. Is there a reason for updating `self.enabled` only if its `Falsy`?

I can't recall exactly why I did it this way... Wish I had commented it.

However, I *believe" the reason I had to include this check was because in the initial data pull from wyze it doesn't include any information for the keypad. So, you need to have the check false for the initial data pull them toggle it to true when you start querying the lock's API. That's when you'll get keypad battery info. 

You don't need the same for the lock battery because the lock always has a battery.

**Comment by ninadpchaudhari** [comment]
Thanks! Certainly makes sense, thanks for sharing :) 
I am trying to debug this entire project in my free time, will add some documentation down the road too. I am also referring from other reverse engineering project [Wyze-sdk](https://wyze-sdk.readthedocs.io/en/latest/) to get any insights.

Regarding this particular PR, 
please do approve the merge that way #311 would be fixed.

**Review by yoinx — APPROVED** [review]
Looks good

**Comment by yoinx** [comment]
I've approved both of these. I leave the merges to Josh. 

Thanks for the effort getting these fixed

**Review by JoshuaMulliken — APPROVED** [review]
Awesome thanks for the patch!

**Comment by yoinx** [comment]
Not sure what happened here, but my keypad battery entirety doesn't appear to be enabled anymore with this change.

**Pull request merged**
